apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: backend-deployment
  namespace: chat-app
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-cont
          image: yashpatil1678/backend:latest
          ports:
            - containerPort: 5001
          env:
            - name: NODE_ENV
              value: production
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-secrets
                  key: mongodb-url 
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: mongodb-secrets
                  key: jwt
            - name: PORT
              value: "5001"
